#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'TSRToLedsMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 2

# The Active Message type associated with this message.
AM_TYPE = 6

class TSRToLedsMsg(tinyos.message.Message.Message):
    # Create a new TSRToLedsMsg of size 2.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=2):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <TSRToLedsMsg> \n"
        try:
            s += "  [led_mask=0x%x]\n" % (self.get_led_mask())
        except:
            pass
        try:
            s += "  [on=0x%x]\n" % (self.get_on())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: led_mask
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'led_mask' is signed (False).
    #
    def isSigned_led_mask(self):
        return False
    
    #
    # Return whether the field 'led_mask' is an array (False).
    #
    def isArray_led_mask(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'led_mask'
    #
    def offset_led_mask(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'led_mask'
    #
    def offsetBits_led_mask(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'led_mask'
    #
    def get_led_mask(self):
        return self.getUIntElement(self.offsetBits_led_mask(), 8, 1)
    
    #
    # Set the value of the field 'led_mask'
    #
    def set_led_mask(self, value):
        self.setUIntElement(self.offsetBits_led_mask(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'led_mask'
    #
    def size_led_mask(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'led_mask'
    #
    def sizeBits_led_mask(self):
        return 8
    
    #
    # Accessor methods for field: on
    #   Field type: short
    #   Offset (bits): 8
    #   Size (bits): 8
    #

    #
    # Return whether the field 'on' is signed (False).
    #
    def isSigned_on(self):
        return False
    
    #
    # Return whether the field 'on' is an array (False).
    #
    def isArray_on(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'on'
    #
    def offset_on(self):
        return (8 / 8)
    
    #
    # Return the offset (in bits) of the field 'on'
    #
    def offsetBits_on(self):
        return 8
    
    #
    # Return the value (as a short) of the field 'on'
    #
    def get_on(self):
        return self.getUIntElement(self.offsetBits_on(), 8, 1)
    
    #
    # Set the value of the field 'on'
    #
    def set_on(self, value):
        self.setUIntElement(self.offsetBits_on(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'on'
    #
    def size_on(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'on'
    #
    def sizeBits_on(self):
        return 8
    
